name: Update instance
on:
  push:
    branches:
      - main
concurrency: serialize
env:
  TEMPLATE: cookiecutter-nanosystemslab
  PROJECT: cookiecutter-nanosystemslab-instance
jobs:
  instance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ env.TEMPLATE }}
        uses: actions/checkout@v3
        with:
          path: ${{ env.TEMPLATE }}
      - name: Check out ${{ env.PROJECT }}
        uses: actions/checkout@v3
        with:
          repository: "nanosystemslab/${{ env.PROJECT }}"
          path: ${{ env.PROJECT }}
          token: ${{ secrets.X_GITHUB_TOKEN }}
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install cutty
        working-directory: ${{ env.TEMPLATE }}
        run: |
          pip install --constraint=.github/workflows/constraints.txt cutty
          cutty --version
      - name: Import commit into ${{ env.PROJECT }}
        run: |
          cutty import --non-interactive --cwd=${PROJECT} --revision=${GITHUB_SHA}
        env:
          GIT_AUTHOR_NAME: "GitHub Action"
          GIT_AUTHOR_EMAIL: "action@github.com"
      - name: Push to nanosystemslab/${{ env.PROJECT }}
        run: |
          if ! git -C ${TEMPLATE} show --no-patch --format=%B ${GITHUB_SHA} | grep -q ^Retrocookie-Original-Commit:
          then
            git -C $PROJECT push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/nanosystemslab/$PROJECT.git HEAD:main
          fi
